# Generated by Django 4.2.21 on 2026-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='emoji',
            field=models.CharField(default='🛒', max_length=10),
        ),
        migrations.AddField(
            model_name='producte',
            name='emoji',
            field=models.CharField(default='🛒', max_length=10),
        ),
    ]
