# Generated by Django 4.2.21 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categoria_emoji_producte_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='imatge_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
