# Generated by Django 4.2.21 on 2026-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_producte_imatge_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='dies_avis_caducitat',
            field=models.IntegerField(default=5),
        ),
    ]
