# Generated by Django 4.2.21 on 2026-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usuari_dies_avis_caducitat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteinventari',
            options={'ordering': ['data_caducitat']},
        ),
        migrations.AlterUniqueTogether(
            name='producteinventari',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producte',
            name='dies_caducitat_aprox',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
