# Generated by Django 4.2.21 on 2026-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_producteinventari_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecepta',
            name='nom_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recepta',
            name='dietes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='instruccions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='intolerancias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='porcions',
            field=models.IntegerField(default=1),
        ),
    ]
