# Generated by Django 4.2.21 on 2026-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ingredientrecepta_nom_original_recepta_dietes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='ingredients_no_vinculats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
