# Generated by Django 4.2.21 on 2026-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_recepta_ingredients_no_vinculats'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='sinonims',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
