# Generated by Django 4.2.21 on 2026-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_producte_sinonims'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='descripcio_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='dietes_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='instruccions_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='intolerancias_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='nom_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
