# Generated by Django 4.2.21 on 2026-05-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_recepta_descripcio_en_recepta_dietes_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepta',
            name='imatge_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
