# Generated by Django 4.2.21 on 2026-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_recepta_imatge_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecepta',
            name='unitat',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'mililitres'), ('L', 'litres'), ('unitat', 'unitat'), ('unitats', 'unitats')], max_length=10),
        ),
    ]
