// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/receptes/screens/recepta_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:frontend/features/inventari/models/inventory_item_model.dart'
    as _i7;
import 'package:frontend/features/inventari/providers/inventory_provider.dart'
    as _i6;
import 'package:frontend/features/receptes/providers/receptes_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReceptesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceptesProvider extends _i1.Mock implements _i2.ReceptesProvider {
  MockReceptesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasMore => (super.noSuchMethod(
        Invocation.getter(#hasMore),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.Recepta> get receptes => (super.noSuchMethod(
        Invocation.getter(#receptes),
        returnValue: <_i2.Recepta>[],
      ) as List<_i2.Recepta>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get total => (super.noSuchMethod(
        Invocation.getter(#total),
        returnValue: 0,
      ) as int);

  @override
  String get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#search),
        ),
      ) as String);

  @override
  List<String> get dietes => (super.noSuchMethod(
        Invocation.getter(#dietes),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get modeRecomanacions => (super.noSuchMethod(
        Invocation.getter(#modeRecomanacions),
        returnValue: false,
      ) as bool);

  @override
  bool get nomesInventari => (super.noSuchMethod(
        Invocation.getter(#nomesInventari),
        returnValue: false,
      ) as bool);

  @override
  bool get nomesUrgents => (super.noSuchMethod(
        Invocation.getter(#nomesUrgents),
        returnValue: false,
      ) as bool);

  @override
  List<int> get productesSeleccionats => (super.noSuchMethod(
        Invocation.getter(#productesSeleccionats),
        returnValue: <int>[],
      ) as List<int>);

  @override
  List<_i2.Recomanacio> get recomanacions => (super.noSuchMethod(
        Invocation.getter(#recomanacions),
        returnValue: <_i2.Recomanacio>[],
      ) as List<_i2.Recomanacio>);

  @override
  bool get loadingDetall => (super.noSuchMethod(
        Invocation.getter(#loadingDetall),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.FavoritItem> get favorits => (super.noSuchMethod(
        Invocation.getter(#favorits),
        returnValue: <_i2.FavoritItem>[],
      ) as List<_i2.FavoritItem>);

  @override
  bool get loadingFavorits => (super.noSuchMethod(
        Invocation.getter(#loadingFavorits),
        returnValue: false,
      ) as bool);

  @override
  bool get teFiltresActius => (super.noSuchMethod(
        Invocation.getter(#teFiltresActius),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool esFavorit(String? idApi) => (super.noSuchMethod(
        Invocation.method(
          #esFavorit,
          [idApi],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isToggling(String? idApi) => (super.noSuchMethod(
        Invocation.method(
          #isToggling,
          [idApi],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setSearch(String? v) => super.noSuchMethod(
        Invocation.method(
          #setSearch,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDietes(List<String>? v) => super.noSuchMethod(
        Invocation.method(
          #setDietes,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMaxTemps(int? v) => super.noSuchMethod(
        Invocation.method(
          #setMaxTemps,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProducte(
    int? id,
    String? nom,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setProducte,
          [
            id,
            nom,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setModeRecomanacions(bool? v) => super.noSuchMethod(
        Invocation.method(
          #setModeRecomanacions,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNomesInventari(bool? v) => super.noSuchMethod(
        Invocation.method(
          #setNomesInventari,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNomesUrgents(bool? v) => super.noSuchMethod(
        Invocation.method(
          #setNomesUrgents,
          [v],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProductesSeleccionats(List<int>? ids) => super.noSuchMethod(
        Invocation.method(
          #setProductesSeleccionats,
          [ids],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFiltres() => super.noSuchMethod(
        Invocation.method(
          #clearFiltres,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> fetchReceptes({bool? loadMore = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchReceptes,
          [],
          {#loadMore: loadMore},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchDetall(String? idApi) => (super.noSuchMethod(
        Invocation.method(
          #fetchDetall,
          [idApi],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchFavorits() => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorits,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorit(String? idApi) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorit,
          [idApi],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [InventoryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryProvider extends _i1.Mock implements _i6.InventoryProvider {
  MockInventoryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.InventoryItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i7.InventoryItem>[],
      ) as List<_i7.InventoryItem>);

  @override
  List<_i7.InventoryItem> get expiringItems => (super.noSuchMethod(
        Invocation.getter(#expiringItems),
        returnValue: <_i7.InventoryItem>[],
      ) as List<_i7.InventoryItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get totalItems => (super.noSuchMethod(
        Invocation.getter(#totalItems),
        returnValue: 0,
      ) as int);

  @override
  int get urgentCount => (super.noSuchMethod(
        Invocation.getter(#urgentCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> fetchInventory() => (super.noSuchMethod(
        Invocation.method(
          #fetchInventory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchExpiringItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchExpiringItems,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> addItem({
    required int? producteId,
    required double? quantitat,
    required String? unitat,
    DateTime? dataCaducitat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [],
          {
            #producteId: producteId,
            #quantitat: quantitat,
            #unitat: unitat,
            #dataCaducitat: dataCaducitat,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateItem(
    int? itemId, {
    required double? quantitat,
    required String? unitat,
    DateTime? dataCaducitat,
    bool? clearDate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [itemId],
          {
            #quantitat: quantitat,
            #unitat: unitat,
            #dataCaducitat: dataCaducitat,
            #clearDate: clearDate,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteItem(int? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i7.InventoryItem? getItemById(int? id) =>
      (super.noSuchMethod(Invocation.method(
        #getItemById,
        [id],
      )) as _i7.InventoryItem?);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
